# name: CI for PyTorch Model
#
# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
#
# jobs:
#   build-and-push:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: rajubuet24
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: ${{ github.ref == 'refs/heads/master' }}
#           tags: |
#             rajubuet24/vit-trajectory:latest
#             rajubuet24/vit-trajectory:${{ github.sha }}
#           platforms: linux/amd64
#
#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}

name: CI for PyTorch Model

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rajubuet24
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            rajubuet24/vit-trajectory:latest
            rajubuet24/vit-trajectory:${{ github.sha }}
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-and-test:
    runs-on: self-hosted
    needs: build-and-push  # Ensures this job runs after the image is built
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Sanity Check in Docker Container
        run: |
          docker pull rajubuet24/vit-trajectory:latest
          docker run --rm --gpus all\
            -v /data1/karim/vit_trajectory/Data/train_dataset.csv:/app/Data/train_dataset.csv \
            -v /data1/karim/vit_trajectory/Data/test_dataset.csv:/app/Data/test_dataset.csv \
            -v /data1/karim/vit_trajectory/snapshot/best_test_model.pth:/app/snapshot/best_test_model.pth \
            rajubuet24/vit-trajectory:latest python main.py --phase=test | tee output.log
        shell: bash

      - name: Display Results
        run: |
          # Extract values from the output log file
          fde=$(grep -oP '(?<=fde: ).*' output.log | tail -1)
          ade=$(grep -oP '(?<=ade: ).*' output.log | tail -1)
          fiou=$(grep -oP '(?<=fiou: ).*' output.log | tail -1)
          test_loss=$(grep -oP '(?<=test_loss: ).*' output.log | tail -1)
          echo "FDE: $fde"
          echo "ADE: $ade"
          echo "FIOU: $fiou"
          echo "Test Loss: $test_loss"
