# name: CI for PyTorch Model
#
# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
#
# jobs:
#   build-and-push:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: rajubuet24
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: ${{ github.ref == 'refs/heads/master' }}
#           tags: |
#             rajubuet24/vit-trajectory:latest
#             rajubuet24/vit-trajectory:${{ github.sha }}
#           platforms: linux/amd64
#
#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
name: CI for PyTorch Model

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (if not already installed on self-hosted runner)
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Adjust to match your self-hosted runner's environment

      - name: Install dependencies (optional if dependencies are pre-installed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure requirements.txt includes all necessary libraries

      - name: Run Sanity Check
        id: sanity_check
        run: |
          python main.py --phase=test | tee output.log
        shell: bash

      - name: Display Results
        run: |
          # Extract values from the output log file
          fde=$(grep -oP '(?<=fde: ).*' output.log | tail -1)
          ade=$(grep -oP '(?<=ade: ).*' output.log | tail -1)
          fiou=$(grep -oP '(?<=fiou: ).*' output.log | tail -1)
          test_loss=$(grep -oP '(?<=test_loss: ).*' output.log | tail -1)
          echo "FDE: $fde"
          echo "ADE: $ade"
          echo "FIOU: $fiou"
          echo "Test Loss: $test_loss"

  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rajubuet24
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            rajubuet24/vit-trajectory:latest
            rajubuet24/vit-trajectory:${{ github.sha }}
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
